### ISSUE TITLE
Uncaught TypeError: Cannot read property 'className' of null

### ISSUE THREAD

**Issue by kgchoy** [muggy8/Orbitar#19]
Error occurs when loading any page. Chrome says it's linked to line 79 of the JavaScript file in the manageMenu function.

``` javascript
if (scheduler.className.indexOf(" schedulerInMenu") > -1){
    scheduler.className = scheduler.className.replace(" schedulerInMenu", ""); 
}
```

**Comment by muggy8** [comment]
This problem is caused by the script wanting to run and needing spcific elements of spicific IDs which doesn't exist on other pages other than the main page. to fix this error, I put an if statement to check weather or not we are on the main page and if we are we can continue with the rest of the program but if we aren't then forget about the rest of it and only worry about moving things like the nav bar objects to where they are supposed to be.
